# Generated by Django 5.2.4 on 2025-08-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
